// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlOeFzyNjNl3BOdwhEWgy5CvOIYPSZvgg',
    appId: '1:850938603969:web:2dd1b4226fceb9c85a2740',
    messagingSenderId: '850938603969',
    projectId: 'service-hub-26d86',
    authDomain: 'service-hub-26d86.firebaseapp.com',
    storageBucket: 'service-hub-26d86.firebasestorage.app',
    measurementId: 'G-SYTHW1JVDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjkcsTUp0AUIi6L6dPwMFSbBpBbqwbgIo',
    appId: '1:850938603969:android:bd44b77c69c08e1f5a2740',
    messagingSenderId: '850938603969',
    projectId: 'service-hub-26d86',
    storageBucket: 'service-hub-26d86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4VK5zwM8D9ZVwl06iu1DFIDl2WDGD67A',
    appId: '1:850938603969:ios:e61b67d1401acdf45a2740',
    messagingSenderId: '850938603969',
    projectId: 'service-hub-26d86',
    storageBucket: 'service-hub-26d86.firebasestorage.app',
    iosBundleId: 'com.example.serviceHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4VK5zwM8D9ZVwl06iu1DFIDl2WDGD67A',
    appId: '1:850938603969:ios:e61b67d1401acdf45a2740',
    messagingSenderId: '850938603969',
    projectId: 'service-hub-26d86',
    storageBucket: 'service-hub-26d86.firebasestorage.app',
    iosBundleId: 'com.example.serviceHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlOeFzyNjNl3BOdwhEWgy5CvOIYPSZvgg',
    appId: '1:850938603969:web:ea3ee82f96c5cf895a2740',
    messagingSenderId: '850938603969',
    projectId: 'service-hub-26d86',
    authDomain: 'service-hub-26d86.firebaseapp.com',
    storageBucket: 'service-hub-26d86.firebasestorage.app',
    measurementId: 'G-JS2E9W0K19',
  );
}
